#ifndef _IOTA_ERROR_TYPE_H_
#define _IOTA_ERROR_TYPE_H_

#define IOTA_SUCCESS 0
#define IOTA_FAILURE -1
#define IOTA_PARAMETER_EMPTY -101
#define IOTA_RESOURCE_NOT_AVAILABLE -102
#define IOTA_INITIALIZATION_REPEATED -103
#define IOTA_LIBRARY_LOAD_FAILED -104
#define IOTA_SECRET_ENCRYPT_FAILED -105
#define IOTA_MQTT_CONNECT_FAILED -106
#define IOTA_MQTT_CONNECT_EXISTED -107
#define IOTA_CERTIFICATE_NOT_FOUND -108
#define IOTA_MQTT_DISCONNECT_FAILED -109
#define IOTA_PARSE_JSON_FAILED -110
#define IOTA_PARAMETER_ERROR -111
#define IOTA_NUMBER_EXCEEDS -112

#endif

